### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PRElias** [nonnymoose/xsr#101]
Hi
Is there a way to use it on WSL2? I already got it how to open Google Chrome, but I don't know hot to start both. Is htere any tutorial?
Thanks

**Comment by lezsakdomi** [comment]
Hi!

Sorry for the late reply.

This script uses `scrot` to take screenshots and `xinput` to detect input events - try taking screenshots with that and if that works this script should also work.

I think xsr should work on WSL too, but there's no tutorial for it I know of. Just make sure you are using X11 and open two terminals: Run chrome from one, and xsr from the other.

Feel free to reopen if you are having issues specific to WSL2.
