### ISSUE TITLE
Add the ability to capture only one window at a time

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#11]
This feature is not implemented in the original program, but we can make it better :)

**Comment by nonnymoose** [comment]
From `man xinput`:
```
--test-xi2 [--root] [device]
               Register for a number of XI2 events  and  display  them.  If  a
               device  is  given, only events on this device are displayed. If
               --root is given, events are selected on the root  window  only.
               Otherwise, a new client window is created (similar to xev).
```

This does not support choosing a different window, so we'd have to change a lot of code and use `xev` or something else.

**Comment by lezsakdomi** [comment]
@nonnymoose I meant capturing the screenshot of one window at a time.
Not a bad idea. I leave this issue as-is, but created #17
