### ISSUE TITLE
Don't record keystrokes in branch master

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#14]
This is what the branch _enhanced_ is for.

**Comment by nonnymoose** [comment]
@lezsakdomi What do you mean?

**Comment by lezsakdomi** [comment]
This is just my idea (I planned to leave review possibility for you, of course).

I think, we should have two main branches: The `master` and the `enhanced`.

As you stated in the readme, this is a _copy_ of the PSR.
We should do as you stated: Making a _copy_ only, not adding features.
My idea is to push implementations basically to `master`, except our own ideas: We should push them into `enhanced`.
And time-to-time pull changes from `master` to `enhanced`.

**Comment by nonnymoose** [comment]
@lezsakdomi I like the idea, but how about this:
`clone` branch or something similar that matches the functionality of PSR, and
`master` branch which has the enhanced version as the default.

The reason I want this is I wanted this project to fill in some of PSR's gaps, for example, difficult-to-edit MHTML output and inability to record keystrokes.

What do you think?

**Comment by lezsakdomi** [comment]
@nonnymoose You have right.
Maybe setting the default branch is the best solution.

One of the following is true:
* What if somebody wants to implement the MHTML format? Then we would pull his/her changes into the enhanced version!
* What if somebody wants to implement the capture-foreground-only feature? Then we would pull his/her changes into the copy version!

I think, that the best solution is maybe a middlepoint:
* Leaving master branch as default (+localisation)
* Adding copy for copy-only (+MHTML, -recorded keystrokes)
* Adding an enhanced branch for enhancments (+foreground only capturing)

**Comment by nonnymoose** [comment]
@lezsakdomi I just realized:
We don't need extra branches for any of this. We can just add different command-line options.
For example, `--direct-clone: implies --mhtml and --no-record-keystrokes`.
