### ISSUE TITLE
Add the ability to capture screenshot only on foreground window

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#17]
This feature is not implemented in the original program, but we can make it better :)

Fork of #11

**Comment by lezsakdomi** [comment]
@nonnymoose I've done it once, but I lost my changes, so I couldn't commit it as-is.
Do you still want to do it? (We should not push in parallel)

**Comment by nonnymoose** [comment]
@lezsakdomi This actually might be fairly simple:
The `--focused` option to `scrot` would do this; however, it would break adding the mouse to screenshots.

**Comment by nonnymoose** [comment]
@lezsakdomi You can do it, but please make it an option.

**Comment by nonnymoose** [comment]
This was also fixed in d3bc6c1.
