### ISSUE TITLE
In the case of no extension

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#36]
... `$outfilename_noext` won't get a value.
Please handle this case specially, or put a comment if it's normal at least!

**Comment by nonnymoose** [comment]
@lezsakdomi Actually, it will.
`$ perl`
```
$outfilename = "myfile";
$outfilename_noext = $outfilename;
$outfilename_noext =~ s/\.[^\.]*$//;
print $outfilename_noext . "\n";
[ctrl+d]
myfile
```

**Comment by lezsakdomi** [comment]
Then add a comment, please!

//I'll do

**Comment by lezsakdomi** [comment]
Sorry, yes, I were dumb
