### ISSUE TITLE
Store mousegrabs internally

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#46]
Store them in an array, rather than spinning up the HDD for this

**Comment by nonnymoose** [comment]
@lezsakdomi Good idea but it still shouldn't be spinning up your HDD... it writes them to /tmp which is a tmpfs that is not usually mounted on the HDD unless you're swapping.

**Comment by lezsakdomi** [comment]
Ok, you have right. But this file really shouldn't supposed to be editable by the user. BTW this causes problems at me (because of the double finishing) as you see in #27 . Could solve some problem temporary.

**Comment by nonnymoose** [comment]
This will actually be a little bit more difficult than I originally thought because we'll have to open the xdotool input instead of simply redirecting it to a file.
