### ISSUE TITLE
finish() calls twice on SIGTERM

### ISSUE THREAD

**Issue by nonnymoose** [nonnymoose/xsr#56]
Discussion for a new bug discovered in #27

**Comment by nonnymoose** [comment]
@lezsakdomi I've found the problem. When you press `ctrl+c`, it exits `MAINLOOP` and _does not terminate the execution of the rest of the program_ (as it probably should). `finish()` is then executed by `sigtrap`, and it interferes with the other finish routine.

This is really weird, because I'm certain that perl _didn't_ do this while I was developing it. (I only added the break shortcut after the first release!)

**Comment by lezsakdomi** [comment]
Note that`Break` does not work for me by the way

I'll discover and resolve this bug later (a few weeks/months)

**Comment by nonnymoose** [comment]
@lezsakdomi Just for the sake of clarity, I'd like to keep this issue closed, as I've technically solved the original problem.
We can make a separate issue for the `Break` key not working.

**Comment by lezsakdomi** [comment]
Revert opening (see #63)

**Comment by lezsakdomi** [comment]
@nonnymoose You were faster :(

**Comment by nonnymoose** [comment]
Oh, oops. Sorry! :)
