### ISSUE TITLE
Run fails on Travis

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#68]
Here's the log: https://travis-ci.org/lezsakdomi/xsr/jobs/287845530#L472
I think, here should be some version mismatch

**Comment by lezsakdomi** [comment]
@nonnymoose Could you please debug this problem?
The log contains a lot of information about the environment.

**Comment by lezsakdomi** [comment]
@nonnymoose If you do so, please create a separate branch for the issue, merge it to master, but don't delete the issue branch: I'll merge it into `67-ci` locally, push to `lezsakdomi/xsr` for test, and if everything works, push the changes to this repo too and create a PR, attaching the instructions for Travis setup.

After than could be the issue branch deleted.

**Comment by lezsakdomi** [comment]
And of course if it isn't a bug in `master`, please let me know and modify the tags accordingly.

**Comment by nonnymoose** [comment]
@lezsakdomi I'm really sorry, I've been so busy.

I looked in the log but it says the build was successful. What problem did you notice?

**Comment by lezsakdomi** [comment]
@nonnymoose On line 478 you can see, that _"perl exited due to compilation errors"_, so the output of `xsr` were [missed from `README.md`](https://github.com/lezsakdomi/xsr/commit/6d666e84ad3f8b0f4649ec69876815f076b37c4b) (this is not the original commit, but has the same problem. Here is the corresponding log: https://travis-ci.org/lezsakdomi/xsr/jobs/287853197#L477)

**Comment by nonnymoose** [comment]
@lezsakdomi I see the problem, but there's nothing in the build log. I'm going to try to debug it.

**Comment by nonnymoose** [comment]
@lezsakdomi It works fine on my computer. I have no idea what happened with Travis...

**Comment by lezsakdomi** [comment]
Lol, it passes without installing any dependencies: <https://travis-ci.org/lezsakdomi/xsr/builds/308551303>
