### ISSUE TITLE
The help output could break README.md.m4

### ISSUE THREAD

**Issue by nonnymoose** [nonnymoose/xsr#72]
@lezsakdomi This is your territory :)

If I put a comma in the help output in xsr, running `make` will print out the following warning:
```
m4:README.md.m4:16: Warning: excess arguments to builtin `m4_patsubst' ignored
```
It will then only include the characters up to the comma in README, and add "`m4_dnl`" to the end. ([Example](https://github.com/nonnymoose/xsr/files/1491838/README.md.broken.txt))

**Comment by lezsakdomi** [comment]
Sorry for not responding.
I've discovered, that the comma caused the bug, but still thinking of a good solution.
Altough I think, that changing main code could be merged without README.md regeneration and fixed in a later commit if needed, I think.

**Comment by lezsakdomi** [comment]
Here's a hotfix: [f4a7099](https://github.com/nonnymoose/xsr/commit/f4a70992abd0d3a16cb54c91dfeebc72e2f9080c)
