### ISSUE TITLE
Choose and use a (build) and deploy system

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#85]

**Comment by lezsakdomi** [comment]
I could recommend
* __dzil__ (as I discovered it at trying to localize)
* plain (or GNU-) __make__
* Perforce's __jam__

**Comment by lezsakdomi** [comment]
Please not that I'll use make with GNU extensions until we decide on something. That's easy to migrate.

**Comment by nonnymoose** [comment]
I like GNU make the most.

**Comment by lezsakdomi** [comment]
Since I am already using it, this could be closed silently :)
